# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0b00f3f7bc12017a132f7e5db8fc0225bf50e32013430b21a6b9c2db261d66875c3c938c90e2ed44d0a66021c521651f111216c6f930b514aefdafae77645ee

test:
  secret_key_base: ad3eb356fdafd1f3c636d0c1cb5e6ad1a9432c55636cb0bc575b75c7506cc981481c7ec87fab36ae91babad2a8d9f10672ede7b014f3fb788fcd3d55a601012b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
